---
- hosts: localhost
- name: Status of Apache
    command: service httpd status
    register: output
    
  vars:
    - slack_domain: yourusername.slack.com
    - slack_token: thetoken/generatedby/slack    

- name: Send notification to Slack
     module: slack
     token: "{{ slack_token }}"
     channel: "#ansible"
     msg: "Status of apache on host {{ ansible_hostname }} is {{ output.stdout_lines }}"
     
- name: Send a message with a link using Slack markup
  slack:
    token: "{{ slack_token }}"
    msg: We sent this message using <https://www.ansible.com|Ansible>!     
    
    
